language: python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest
env: PYTHONPATH=$(PWD)/src:$(PWD)
script:
  - pylint src/*
  - cd tests/unit; pytest *
