language: python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/src:$TRAVIS_BUILD_DIR
script:
  - pylint src/*
  - cd tests/unit; pytest *
